version: '3.8'

networks:
  web2412:
    driver: bridge
#  laravel:
#    driver: bridge
#  shared_network:
#    external: true

volumes:
  #  cron_volume:
  caddy_caddyfile:
  #shared_caddyfile:   # Добавляем том для общего использования файла Caddyfile

services:

  caddy:
    container_name: caddy
    image: caddy:2.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/config:/config/caddy
      - caddy_caddyfile:/etc/caddy

      # tfmf
      #        - '${FOLDER_2412JOB_SITE1}:${FOLDER_2412JOB_SITE1_SERV}'
      #        - '${FOLDER_CMS2_DEV}:${FOLDER_CMS2_DEV_SERV}'
      #        - '${FOLDER_TFMF_RU}:${FOLDER_TFMF_RU_SERV}'
      # tfmf - cms23
      - '${FOLDER_CMS23_DEV}:${FOLDER_CMS23_DEV_SERV}'

        # vitius
        #        - '${FOLDER_VT2412_DEV}:${FOLDER_VT2412_SERV}'
        #        - '${FOLDER_2309LIVEWIRE}:${FOLDER_2309LIVEWIRE_SERV}'


        #        - '${FOLDER_2309LIVEWIRE}:${FOLDER_2309LIVEWIRE_SERV}'
        #        - '${FOLDER_SITE_API}:${FOLDER_SITE_API_SERV}'
        #        - '${FOLDER_BASE12NAREK}:${FOLDER_BASE12NAREK_SERV}'
        #        - '${FOLDER_2410SVO}:${FOLDER_2410SVO_SERV}'

        #- shared_caddyfile:/shared/caddyfile  # Монтируем том для общего использования файла
        #- shared_caddyfile:/etc/caddy
        #- shared_caddyfile:/etc/caddy/Caddyfile

      #- ./caddy/log:/var/log/caddy
    #      #      - ${FOLDER_UPR_SERV}/storage/app/caddy:/etc/caddy
    ##      - caddy_caddyfile:/caddy/Caddyfile
    ##      - caddy_caddyfile:/caddy
    ##      - caddy_caddyfile:/etc/caddy
    ##      - caddy_caddyfile:./caddy
    ##      - caddy_caddyfile:/etc/caddy/Caddyfile
    ##      - caddy_caddyfile:/caddy
    ##      - caddyfile:/caddy/Caddyfile
    ##      - '${FOLDER_UPR_SERV}/storage/app/caddyfile33/:/etc/caddy/Caddyfile'
    ###      - '${FOLDER_2309LIVEWIRE}:/2309livewire'
    ###      - '${FOLDER_TEST231012}:${FOLDER_TEST231012_SERV}'
    ##      - '${FOLDER_2302DIDRIVE}:${FOLDER_2302DIDRIVE_CADDY}'
    ##      - '${FOLDER_TEST23116PHP}:${FOLDER_TEST23116PHP_SERV}'
    ##      - '${FOLDER_UPR_SERV}:${FOLDER_UPR_SERV_SERV}'
    ##      -  '/etc/caddy/Caddyfile:${FOLDER_UPR_SERV_SERV}/storage/app/caddyfile2'
    ##      -  './caddy/Caddyfile:${FOLDER_UPR_SERV_SERV}/storage/app/caddyfile2'
    ##      - '${FOLDER_2401TEST}:${FOLDER_2401TEST_SERV}'
    #
    #
    #      - '${FOLDER_2312AUTO_AS}:${FOLDER_2312AUTO_AS_SERV}'
    #      - '${FOLDER_2312AUTO_AS__DIR_PHOTO}:${FOLDER_2312AUTO_AS_SERV}/storage/app/public/photo'
    #      - '${FOLDER_2312AUTO_AS_DIDRIVE}:${FOLDER_2312AUTO_AS_DIDRIVE_SERV}'
    #      - '${FOLDER_API_PHP74}:${FOLDER_API_PHP74_SERV}'
    #
    #      - '${FOLDER_BASE17}:${FOLDER_BASE17_SERV}'
    #      - '${FOLDER_BASE16}:${FOLDER_BASE16_SERV}'
    #      - '${FOLDER_2308BEGET}:${FOLDER_2308BEGET_SERV}'
    #      - '${FOLDER_BITRIX1}:${FOLDER_BITRIX1_SERV}'
    #      - './../2407bitrix24:/home/bitrix24'

    depends_on:
      #tfmf
      - db_mysql2412
      - cms23_dev
    #        - mf__tfmf_ru
    #        - 2412job_site1
    #        - cms22_dev
    networks:
      - web2412

  ########### tfmf ################


  db_mysql2412:
    container_name: db_mysql2412
    image: mariadb:10.7.8
    networks:
      #        - laravel
      - web2412
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
    #      ports:
    #        - 3306:3306
    volumes:
      - '${MYSQL2412_DB_FOLDER}:/var/lib/mysql'
    restart: unless-stopped

  phpmyadmin2412:
    image: phpmyadmin/phpmyadmin
    links:
      - db_mysql2412:db
    ports:
      - 6061:80
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M
    depends_on:
      - db_mysql2412
    networks:
      #        - laravel
      - web2412


  # tfmf_ru
  #    mf__tfmf_ru:
  #      container_name: mf__tfmf_ru
  #      depends_on:
  #        - db_mysql2412
  #      networks:
  #        #        - laravel
  #        #        - shared_network
  #        - web2412
  #      build:
  #        context: .
  #        dockerfile: docker.2412job.mf__tfmf_ru.Dockerfile
  ##        dockerfile: docker.2412livewire.Dockerfile
  #      working_dir: ${FOLDER_TFMF_RU_SERV}
  #      environment:
  #        - PHPGROUP=www-data
  #        - PHPUSER=www-data
  #        - FOLDER=${FOLDER_TFMF_RU_SERV}
  #      restart: unless-stopped
  #      links:
  #        - db_mysql2412:db
  #      expose:
  #        - 9000
  #      volumes:
  #        - '${FOLDER_TFMF_RU}:${FOLDER_TFMF_RU_SERV}'


  # новая cms разработка
  cms23_dev:
    container_name: cms23_dev
    depends_on:
      - db_mysql2412
    networks:
      #        - laravel
      #        - shared_network
      - web2412
    build:
      context: .
      #        dockerfile: docker.2412job.site1.Dockerfile
      #        dockerfile: docker.2309livewire.Dockerfile
      dockerfile: docker.2412livewire.Dockerfile
    working_dir: ${FOLDER_CMS23_DEV_SERV}
    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data
      - FOLDER=${FOLDER_CMS23_DEV_SERV}
    restart: unless-stopped
    links:
      - db_mysql2412:db
    expose:
      - 9000
    volumes:
      - '${FOLDER_CMS23_DEV}:${FOLDER_CMS23_DEV_SERV}'


#
#
#    2412job_site1:
#      container_name: 2412job_site1
#      depends_on:
#        - db_mysql2412
#      networks:
#        #        - laravel
#        #        - shared_network
#        - web2412
#      build:
#        context: .
#        dockerfile: docker.2412job.site1.Dockerfile
#      working_dir: ${FOLDER_2412JOB_SITE1_SERV}
#      environment:
#        - PHPGROUP=www-data
#        - PHPUSER=www-data
#        - FOLDER=${FOLDER_2412JOB_SITE1_SERV}
#      restart: unless-stopped
#      links:
#        - db_mysql2412:db
#      expose:
#        - 9000
#      volumes:
#        - '${FOLDER_2412JOB_SITE1}:${FOLDER_2412JOB_SITE1_SERV}'


#    cms22_dev:
#      container_name: cms22_dev
#      depends_on:
#        - db_mysql2412
#      networks:
#        #        - laravel
#        #        - shared_network
#        - web2412
#      build:
#        context: .
##        dockerfile: docker.2412job.site1.Dockerfile
##        dockerfile: docker.2309livewire.Dockerfile
#        dockerfile: docker.2412livewire.Dockerfile
#      working_dir: ${FOLDER_CMS2_DEV_SERV}
#      environment:
#        - PHPGROUP=www-data
#        - PHPUSER=www-data
#        - FOLDER=${FOLDER_CMS2_DEV_SERV}
#      restart: unless-stopped
#      links:
#        - db_mysql2412:db
#      expose:
#        - 9000
#      volumes:
#        - '${FOLDER_CMS2_DEV}:${FOLDER_CMS2_DEV_SERV}'
#



