version: '3.8'

services:

  caddy:
    container_name: caddy
    image: caddy:2.6.4
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

    volumes:
      - './caddy/Caddyfile:/etc/caddy/Caddyfile'
      - './caddy/config:/config/caddy/'
      - '${BU_PHP_FOLDER}:/srv'
    depends_on:
      - bu72_back
    networks:
      - laravel

  nuxt:
      container_name: nuxt
      # environment:
      #   - APP_ROOT:/nuxt_app
      #   # - BU_FRONT_FOLDER:./../2304bu_nuxt3
      #   - BU_FRONT_FOLDER2:/bu72_front/code
      volumes: 
        # - '${BU_FRONT_FOLDER2}:${APP_ROOT}'
        - './bu72_front/code:/nuxt_app'
      build:
        context: .
        dockerfile: bu72_front/DockerfileNuxt        
      networks:
        - laravel

  bu72_back:
    container_name: bu72_back

    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data
    networks:
      - laravel
    build:
      context: .
      dockerfile: bu72_back/Dockerfile
    restart: unless-stopped
    tty: true
    expose:
      - 9000
    volumes:
      - '${BU_PHP_FOLDER}:/srv'
    depends_on:
      - bu72_mysql2

  bu72_mysql2:
    container_name: bu72_mysql2
    networks:
      - laravel
    image: mariadb:10.7.8

    environment:

      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${BU_DB_ROOT_PASSWORD}

      MYSQL_DATABASE: ${BU_DB_DATABASE}
      MYSQL_USER: ${BU_DB_USERNAME}
      MYSQL_PASSWORD: ${BU_DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - '${BU_FOLDER_DB}:/var/lib/mysql'
    restart: unless-stopped

  #++
  bu72_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - bu72_mysql2:db
    ports:
      - 6060:80
    environment:
      MYSQL_ROOT_PASSWORD: ${BU_DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M
    depends_on:
      - bu72_mysql2
    networks:
      - laravel

# volumes:
#   # scr:
#   Caddyfile:
#   # dataredis:
#   v_mysql:
#   data-www:
#   www47:
#   config:
#   bu72_front:

networks:
  laravel: null
