version: '3.8'

networks:
  laravel: null

services:

  caddy:
    container_name: caddy
    # image: caddy:2.6.4
    image: caddy:2.6
    restart: unless-stopped
    # restart: always

    # build:
    #   context: .
    #   dockerfile: caddy/Dockerfile

    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

    volumes:
      - './caddy/Caddyfile:/etc/caddy/Caddyfile'
      - './caddy/config:/config/caddy/'
      # - 'caddy_certs:/root/.caddy'
      - './caddy/certs:/data/caddy/locks/'
      # - './caddy/certs2:/data/caddy/'
      - './caddy/certs3:/data/caddy/certificates/'
      # - './caddy/certs_lib:/var/lib/caddy/'
      # - './caddy/share:/local/share/caddy/'
      # - './caddy/share2:/.local/share/caddy/'
      # - './caddy/share3:/local/share/'
      # - './caddy/share4:/.local/share/'
      # - './caddy/share5:/usr/share/caddy'
      # - './caddy/share6:/config/'
      # # - '${BU_PHP_FOLDER}:/srv'
      # - '${BU_PHP_FOLDER}:/srv_bu_back'
      # # - '${TTT72_PHP_FOLDER}:/var/www/html/ttt72'
      - '${TTT72_PHP_FOLDER}:/srv/'
      - '${BU_PHP_FOLDER}:/srv_bu_back/'
      - '${BASE17_FOLDER}:/srv_base17/'
      - '${SITE2_PHP_FOLDER}:/site2'

    depends_on:
      - ttt72_laravel
    #   - bu72_back
    networks:
      - laravel
    #   # - ttt72_net

  ttt72_mysql:
    container_name: ttt72_mysql
    networks:
      - laravel
    image: mariadb:10.7.8

    environment:

      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${TTT72_DB_ROOT_PASSWORD}

      MYSQL_DATABASE: ${TTT72_DB_DATABASE}
      MYSQL_USER: ${TTT72_DB_USERNAME}
      MYSQL_PASSWORD: ${TTT72_DB_PASSWORD}
    ports:
      - 3361:3306
    volumes:
      - '${TTT72_FOLDER_DB}:/var/lib/mysql'
    restart: unless-stopped

  # #++
  ttt72_phpmyadmin:
    depends_on:
      - ttt72_mysql
    networks:
      - laravel
    image: phpmyadmin/phpmyadmin
    ports:
      - 6061:80
    links:
      - ttt72_mysql:db
    environment:
      MYSQL_ROOT_PASSWORD: ${TTT72_DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M

  ttt72_laravel:
    container_name: ttt72_laravel

    depends_on:
      - ttt72_mysql

    networks:
      - laravel

    build:
      context: .
      dockerfile: ttt72_laravel/Dockerfile

    working_dir: /srv

    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data

    restart: unless-stopped
    tty: true

    # ports:
    # # #   # - 80:6080    
    #   - 9000:9000
    #   - 81:80
      # - "9900:80"
    # expose:
    #   - 9000    
    # # # #   # - 9061
      
    volumes:
      # - '${TTT72_PHP_FOLDER}:/srv'
      # - '${TTT72_PHP_FOLDER}:/var/www/html/ttt72'
      # - '${TTT72_PHP_FOLDER}:/var/www/html/ttt72'
      - '${TTT72_PHP_FOLDER}:/srv'

  # nodejs:
  #   image: node:alpine
  #   networks:
  #     - laravel
  #   # build: .
  #   volumes:
  #     - .:/usr/app
  #   tty: true





  bu72_mysql2:
    container_name: bu72_mysql2
    networks:
      - laravel
    image: mariadb:10.7.8

    environment:

      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${BU_DB_ROOT_PASSWORD}

      MYSQL_DATABASE: ${BU_DB_DATABASE}
      MYSQL_USER: ${BU_DB_USERNAME}
      MYSQL_PASSWORD: ${BU_DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - '${BU_FOLDER_DB}:/var/lib/mysql'
    restart: unless-stopped

  #++
  bu72_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - bu72_mysql2:db
    ports:
      - 6060:80
    environment:
      MYSQL_ROOT_PASSWORD: ${BU_DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M
    depends_on:
      - bu72_mysql2
    networks:
      - laravel





# #   # app:
  bu72_back:
# #     # container_name: app
    container_name: bu72_back

    networks:
      - laravel
    build:
      context: .
      dockerfile: bu72_back/Dockerfile
# #       # args:
# #       #   - PHPUSER=${PHPUSER:-www-data}
# #       #   - PHPGROUP=${PHPGROUP:-www-data}
# #       # environment:
# #       #   DB_HOST: mysql
# #     restart: unless-stopped
# #     tty: true
# #     expose:
# #       - 9000
# #       # - 9001
# #     volumes:
# #       # - './data-www:/srv'
# #       - '${BU_PHP_FOLDER}:/srv'
# #       # - '${BU_PHP_FOLDER}:/var/www/html'
# #       # - www47:/srv
# #     depends_on:
# #       - bu72_mysql2
# #       # - redis_db
# #       # - mailhog



  # ttt72_laravel:
    # container_name: ttt72_laravel

    # depends_on:
    #   - ttt72_mysql
    # networks:
    #   - laravel

    # build:
    #   context: .
    #   dockerfile: ttt72_laravel/Dockerfile

    working_dir: /srv_bu_back/

    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data

    restart: unless-stopped
    tty: true

    # ports:
    # # #   # - 80:6080    
    #   - 9000:9000
    #   - 81:80
      # - "9900:80"
    expose:
      - 9000
    # # # #   # - 9061
      
    volumes:
      # - '${TTT72_PHP_FOLDER}:/srv'
      # - '${TTT72_PHP_FOLDER}:/var/www/html/ttt72'
      # - '${TTT72_PHP_FOLDER}:/var/www/html/ttt72'
      # - '${TTT72_PHP_FOLDER}:/srv'
      - '${BU_PHP_FOLDER}:/srv_bu_back/'
    







# #   # bu72_front:

# #   #   container_name: bu72_front

# #   #   build:
# #   #     context: .
# #   #     dockerfile: bu72_front/Dockerfile
# #   #     # args:
# #   #     #   - PHPUSER=${PHPUSER:-www-data}
# #   #     #   - PHPGROUP=${PHPGROUP:-www-data}
# #   #     # environment:
# #   #     #   DB_HOST: mysql
# #   #   # command:
# #   #   #   - /npm install
# #   #   #   - /npm run build
# #   #   #   - /node .output/server/index.mjs   
# #   #   # restart: unless-stopped
# #   #   # tty: true
# #   #   # expose:
# #   #   # #   # - 9000
# #   #   # #   - 9005
# #   #   # #   # - 9001
# #   #   #   # - 3000
# #   #   #   - 8080
# #   #   # volumes:
# #   #   # #   # - './data-www:/srv'
# #   #   # #   - '${BU_PHP_FOLDER}:/srv'
# #   #   # #   # - www47:/srv
# #   #   #   # - '${BU_FRONT_FOLDER}:/app'
# #   #   #   - '${BU_FRONT_FOLDER}:/usr/src/app'
# #   #   # ports:
# #   #   # - 8080:8080
# #   #   # working_dir: /var/www/html/avantage
# #   #   # volumes:
# #   #   # # #   # - ./avantage:/var/www/html/avantage
# #   #   # # #   # - ${BU_FRONT_FOLDER}:/var/www/html/avantage
# #   #   # # #   # - '${BU_FRONT_FOLDER}:/usr/src/app'
# #   #   # # #   # - '${BU_FRONT_FOLDER}:/app'
# #   #   # # #   - '/bu72_front/code:/usr/src/app'
# #   #   # #   - /bu72_front/code:/usr/src/app
# #   #   #   - './bu72_front/code:/app'
# #   #   # user: node

# #   #   # payloadExtraction: false

# #   #   # command: sh -c "node .output/server/index.mjs"
# #   #   # stdin_open: true

# #   #   # depends_on:
# #   #   #   # - mysql2
# #   #   #   # - bu72_mysql2
# #   #   #   # - redis_db
# #   #   #   # - mailhog
# #   #   #   - bu72_back
# #   #   networks:
# #   #     - laravel









# volumes:
  # caddy_certs:


  base17:

    container_name: base17

    # depends_on:
    #   - ttt72_mysql
    networks:
      - laravel

    # links:
    #   - base17_mysql:db

    build:
      context: .
      dockerfile: base17.Dockerfile

    working_dir: /srv_base17

    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data

    restart: unless-stopped
    tty: true
    # ports:
    # # #   # - 80:6080    
    #   - 9000:9000
    #   - 81:80
      # - "9900:80"
    expose:
    # # # # #   # - 9061
      - 9000    
    volumes:
      # - '${TTT72_PHP_FOLDER}:/srv'
      # - '${TTT72_PHP_FOLDER}:/var/www/html/ttt72'
      # - '${TTT72_PHP_FOLDER}:/var/www/html/ttt72'
      - '${BASE17_FOLDER}:/srv_base17'

  base17_mysql:
    container_name: base17_mysql
    networks:
      - laravel
    image: mariadb:10.7.8

    environment:

      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${BASE17_DB_ROOT_PASSWORD}

      xMYSQL_DATABASE: ${BU_DB_DATABASE}
      MYSQL_DATABASE: base17
      xMYSQL_USER: ${BU_DB_USERNAME}
      xMYSQL_PASSWORD: ${BU_DB_PASSWORD}
    # ports:
    #   - '33061:3306'
    expose:
      - 3306
    volumes:
      - '${BASE17_FOLDER_DB}:/var/lib/mysql'
    restart: unless-stopped

  #++
  base17_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - base17_mysql:db
    ports:
      - 6090:80
    environment:
      MYSQL_ROOT_PASSWORD: ${BASE17_DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M
    depends_on:
      - base17_mysql
    networks:
      - laravel




  site2:
    container_name: site2

  #   # depends_on:
  #   #   - ttt72_mysql
    networks:
      - laravel

    build:
      context: .
      dockerfile: site2/Dockerfile

    working_dir: /site2

    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data

    restart: unless-stopped
    # tty: true
  #   ports:
  # #   # # #   # - 80:6080    
  # #   #   - 9000:9000
  # #   #   - 81:80
  #     - "9050:9000"
    # expose:
  #   # # # # #   # - 9061
      # - 9050    
    volumes:
  #     # - '${TTT72_PHP_FOLDER}:/srv'
  #     # - '${TTT72_PHP_FOLDER}:/var/www/html/ttt72'
  #     # - '${TTT72_PHP_FOLDER}:/var/www/html/ttt72'
      - '${SITE2_PHP_FOLDER}:/site2'
    

  # nodejs:
  #   image: node:alpine
  #   networks:
  #     - laravel
  #   # build: .
  #   volumes:
  #     - .:/usr/app
  #   tty: true
