version: '3.8'

services:

  caddy:
    container_name: caddy
    image: caddy:2.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - './caddy/Caddyfile:/etc/caddy/Caddyfile'
      - './caddy/config:/config/caddy/'
      - '${FOLDER_2308BEGET}:/2308beget'
      - '${FOLDER_2309LIVEWIRE}:/2309livewire'
    depends_on:
      - db_mysql
      - 2308beget
      - 2309livewire
    networks:
      - laravel



  db_mysql:
    container_name: db_mysql
    image: mariadb:10.7.8
    networks:
      - laravel
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - '${MYSQL_DB_FOLDER}:/var/lib/mysql'
    restart: unless-stopped



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db_mysql:db
    ports:
      - 6061:80
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M
    depends_on:
      - db_mysql
    networks:
      - laravel



  2308beget:
    container_name: 2308beget

    build:
      context: .
      dockerfile: docker.2308beget.Dockerfile
    working_dir: /2308beget
    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - '${FOLDER_2308BEGET}:/2308beget'

    depends_on:
      - db_mysql
    networks:
      - laravel


  2309livewire:
    container_name: 2309livewire
    depends_on:
      - db_mysql
    networks:
      - laravel
    build:
      context: .
      dockerfile: docker.2308beget.Dockerfile
    working_dir: /2309livewire
    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - '${FOLDER_2309LIVEWIRE}:/2309livewire'


  test231012:
    container_name: test231012
    depends_on:
      - db_mysql
    networks:
      - laravel
    build:
      context: .
      dockerfile: docker.test231012.Dockerfile
    working_dir: ${FOLDER_TEST231012_SERV}
    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - '${FOLDER_TEST231012}:${FOLDER_TEST231012_SERV}'



# volumes:
#   caddy_certs:
# #   # scr:
# #   Caddyfile:
# #   # dataredis:
# #   v_mysql:
# #   data-www:
# #   www47:
# #   config:
# #   bu72_front:



networks:
  laravel:
    driver: bridge
  # ttt72_net: null
