version: '3.8'

services:

  caddy:
    container_name: caddy
    # image: caddy:2.6.4
    # image: caddy:2.6
    restart: unless-stopped

    build:
      context: .
      dockerfile: caddy/Dockerfile

    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

    volumes:
      - './caddy/Caddyfile:/etc/caddy/Caddyfile'
      - './caddy/config:/config/caddy/'
      - caddy_certs:/root/.caddy
      # - '${BU_PHP_FOLDER}:/srv'
      # - '${TTT72_PHP_FOLDER}:/var/www/html/ttt72'
      - '${TTT72_PHP_FOLDER}:/srv'
    depends_on:
      - ttt72_laravel
    #   - bu72_back
    networks:
      - laravel
    #   # - ttt72_net



  ttt72_laravel:
    container_name: ttt72_laravel

    # depends_on:
    #   - ttt72_mysql
    networks:
      - laravel

    build:
      context: .
      dockerfile: ttt72_laravel/Dockerfile

    working_dir: /srv/

    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data

    restart: unless-stopped
    tty: true
    # ports:
    # # #   # - 80:6080    
    #   - 9000:9000
    #   - 81:80
      # - "9900:80"
    # expose:
    # # # #   # - 9061
    #   - 9000    
    volumes:
      # - '${TTT72_PHP_FOLDER}:/srv'
      # - '${TTT72_PHP_FOLDER}:/var/www/html/ttt72'
      # - '${TTT72_PHP_FOLDER}:/var/www/html/ttt72'
      - '${TTT72_PHP_FOLDER}:/srv'
    

  # nodejs:
  #   image: node:alpine
  #   networks:
  #     - laravel
  #   # build: .
  #   volumes:
  #     - .:/usr/app
  #   tty: true

  ttt72_mysql:
    container_name: ttt72_mysql
    networks:
      - laravel
    image: mariadb:10.7.8

    environment:

      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${TTT72_DB_ROOT_PASSWORD}

      MYSQL_DATABASE: ${TTT72_DB_DATABASE}
      MYSQL_USER: ${TTT72_DB_USERNAME}
      MYSQL_PASSWORD: ${TTT72_DB_PASSWORD}
    ports:
      - 3361:3306
    volumes:
      - '${TTT72_FOLDER_DB}:/var/lib/mysql'
    restart: unless-stopped


  # #++
  ttt72_phpmyadmin:
    depends_on:
      - ttt72_mysql
    networks:
      - laravel
    image: phpmyadmin/phpmyadmin
    ports:
      - 6061:80
    links:
      - ttt72_mysql:db
    environment:
      MYSQL_ROOT_PASSWORD: ${TTT72_DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M



networks:
  laravel: null



  # nuxt:
  #     container_name: nuxt
  #     # environment:
  #     #   - APP_ROOT:/nuxt_app
  #     #   # - BU_FRONT_FOLDER:./../2304bu_nuxt3
  #     #   - BU_FRONT_FOLDER2:/bu72_front/code
  #     volumes: 
  #       # - '${BU_FRONT_FOLDER2}:${APP_ROOT}'
  #       - './bu72_front/code:/nuxt_app'
  #     build:
  #       context: .
  #       dockerfile: bu72_front/DockerfileNuxt        
  #     networks:
  #       - laravel

  # nuxt_dev:
  #     container_name: nuxt_dev
  #     # environment:
  #     #   - APP_ROOT:/nuxt_app
  #     #   # - BU_FRONT_FOLDER:./../2304bu_nuxt3
  #     #   - BU_FRONT_FOLDER2:/bu72_front/code
  #     volumes: 
  #       # - '${BU_FRONT_FOLDER2}:${APP_ROOT}'
  #       - './bu72_front_dev/code:/nuxt_app'
  #     build:
  #       context: .
  #       dockerfile: bu72_front_dev/DockerfileNuxt        
  #     networks:
  #       - laravel

  # bu72_back:
  #   container_name: bu72_back

  #   environment:
  #     - PHPGROUP=www-data
  #     - PHPUSER=www-data
  #   networks:
  #     - laravel
  #   build:
  #     context: .
  #     dockerfile: bu72_back/Dockerfile
  #   restart: unless-stopped
  #   tty: true
  #   expose:
  #     - 9000
  #   volumes:
  #     - '${BU_PHP_FOLDER}:/srv'
  #   depends_on:
  #     - bu72_mysql2

  # bu72_back_dev:
  #   container_name: bu72_back_dev

  #   environment:
  #     - PHPGROUP=www-data
  #     - PHPUSER=www-data
  #   networks:
  #     - laravel
  #   build:
  #     context: .
  #     dockerfile: bu72_back_dev/Dockerfile
  #   restart: unless-stopped
  #   tty: true
  #   expose:
  #     - 9000
  #   volumes:
  #     - '${BU_PHP_FOLDER_DEV}:/srv'
  #   depends_on:
  #     - bu72_mysql2

  # bu72_mysql2:
  #   container_name: bu72_mysql2
  #   networks:
  #     - laravel
  #   image: mariadb:10.7.8

  #   environment:

  #     MYSQL_ROOT_HOST: "%"
  #     MYSQL_ROOT_PASSWORD: ${BU_DB_ROOT_PASSWORD}

  #     MYSQL_DATABASE: ${BU_DB_DATABASE}
  #     MYSQL_USER: ${BU_DB_USERNAME}
  #     MYSQL_PASSWORD: ${BU_DB_PASSWORD}
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - '${BU_FOLDER_DB}:/var/lib/mysql'
  #   restart: unless-stopped

  # #++
  # bu72_phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   links:
  #     - bu72_mysql2:db
  #   ports:
  #     - 6060:80
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${BU_DB_ROOT_PASSWORD}
  #     UPLOAD_LIMIT: 300M
  #   depends_on:
  #     - bu72_mysql2
  #   networks:
  #     - laravel




















volumes:
  caddy_certs:
#   # scr:
#   Caddyfile:
#   # dataredis:
#   v_mysql:
#   data-www:
#   www47:
#   config:
#   bu72_front:

networks:
  laravel: 
    driver: bridge
  # ttt72_net: null
