version: '3.8'

networks:
#  web2412:
#    driver: bridge
  laravel:
    driver: bridge
#  shared_network:
#    external: true

volumes:
#  cron_volume:
  caddy_caddyfile:
#shared_caddyfile:   # Добавляем том для общего использования файла Caddyfile

services:

  caddy:
    container_name: caddy
    image: caddy:2.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/config:/config/caddy
      - caddy_caddyfile:/etc/caddy

      - '${FOLDER_UBER_DEV}:${FOLDER_UBER_DEV_SERV}'

      # tfmf
      #        - '${FOLDER_2412JOB_SITE1}:${FOLDER_2412JOB_SITE1_SERV}'
      #        - '${FOLDER_CMS2_DEV}:${FOLDER_CMS2_DEV_SERV}'
      #        - '${FOLDER_TFMF_RU}:${FOLDER_TFMF_RU_SERV}'

    depends_on:
      #tfmf
      - db_mysql
      - uber
    #        - mf__tfmf_ru
    #        - 2412job_site1
    #        - cms22_dev
    networks:
      - laravel

  ########### tfmf ################


  db_mysql:
    container_name: db_mysql
    image: mariadb:10.7.8
    networks:
      - laravel
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
    #      ports:
    #        - 3306:3306
    volumes:
      - '${MYSQLUBER_DB_FOLDER}:/var/lib/mysql'
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db_mysql:db
    ports:
      - 6062:80
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M
    depends_on:
      - db_mysql
    networks:
      - laravel



  # tfmf_ru
  #    mf__tfmf_ru:
  #      container_name: mf__tfmf_ru
  #      depends_on:
  #        - db_mysql2412
  #      networks:
  #        #        - laravel
  #        #        - shared_network
  #        - web2412
  #      build:
  #        context: .
  #        dockerfile: docker.2412job.mf__tfmf_ru.Dockerfile
  ##        dockerfile: docker.2412livewire.Dockerfile
  #      working_dir: ${FOLDER_TFMF_RU_SERV}
  #      environment:
  #        - PHPGROUP=www-data
  #        - PHPUSER=www-data
  #        - FOLDER=${FOLDER_TFMF_RU_SERV}
  #      restart: unless-stopped
  #      links:
  #        - db_mysql2412:db
  #      expose:
  #        - 9000
  #      volumes:
  #        - '${FOLDER_TFMF_RU}:${FOLDER_TFMF_RU_SERV}'


  # новая cms разработка
  uber:
    container_name: uber
    depends_on:
      - db_mysql
    networks:
      - laravel
    build:
      context: .
      dockerfile: docker.2503uber.Dockerfile
    working_dir: ${FOLDER_UBER_DEV_SERV}
    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data
      - FOLDER=${FOLDER_UBER_DEV_SERV}
    restart: unless-stopped
    links:
      - db_mysql:db
    expose:
      - 9000
    volumes:
      - '${FOLDER_UBER_DEV}:${FOLDER_UBER_DEV_SERV}'



