version: '3.8'

services:

  caddy:
    container_name: caddy
    image: caddy:2.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - './caddy/Caddyfile:/etc/caddy/Caddyfile'
      - './caddy/config:/config/caddy/'
##      - '${FOLDER_2308BEGET}:/2308beget'
##      - '${FOLDER_2309LIVEWIRE}:/2309livewire'
##      - '${FOLDER_TEST231012}:${FOLDER_TEST231012_SERV}'
#      - '${FOLDER_2302DIDRIVE}:${FOLDER_2302DIDRIVE_CADDY}'
      - '${FOLDER_2309LIVEWIRE}:${FOLDER_2309LIVEWIRE_SERV}'
      - '${FOLDER_TEST23116PHP}:${FOLDER_TEST23116PHP_SERV}'
    depends_on:
      - db_mysql
#      - 2308beget
      - 2309livewire
#      - test231012
#      - 2302didrive
      - test231116php
    networks:
      - laravel



#  redis:
#    container_name: redis
#    image: redis:latest
#    networks:
#      - laravel
#    ports:
#      - "6379:6379"
##    volumes:
##      - '${MYSQL_DB_FOLDER}:/var/lib/mysql'
#    restart: unless-stopped

#
#  memcached:
#    container_name: memcached
#    image: memcached:latest
#    networks:
#      - laravel
##    environment:
##      MYSQL_ROOT_HOST: "%"
##      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
#    ports:
#      - "11211:11211"
##    volumes:
##      - '${MYSQL_DB_FOLDER}:/var/lib/mysql'
#    restart: unless-stopped



  db_mysql:
    container_name: db_mysql
    image: mariadb:10.7.8
    networks:
      - laravel
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - '${MYSQL_DB_FOLDER}:/var/lib/mysql'
    restart: unless-stopped



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db_mysql:db
    ports:
      - 6060:80
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M
    depends_on:
      - db_mysql
    networks:
      - laravel



#  2302didrive:
#    container_name: 2302didrive
#
#    build:
#      context: .
#      dockerfile: ${DOCKERFILE_2302DIDRIVE}
#    working_dir: ${FOLDER_2302DIDRIVE_CADDY}
#    environment:
#      - PHPGROUP=www-data
#      - PHPUSER=www-data
#      - FOLDER=${FOLDER_2302DIDRIVE_CADDY}
#    restart: unless-stopped
#    expose:
#      - 9000
#    volumes:
#      - '${FOLDER_2302DIDRIVE}:${FOLDER_2302DIDRIVE_CADDY}'
#
#    depends_on:
#      - db_mysql
#    networks:
#      - laravel




#  2308beget:
#    container_name: 2308beget
#
#    build:
#      context: .
#      dockerfile: docker.2308beget.Dockerfile
#    working_dir: /2308beget
#    environment:
#      - PHPGROUP=www-data
#      - PHPUSER=www-data
#    restart: unless-stopped
#    expose:
#      - 9000
#    volumes:
#      - '${FOLDER_2308BEGET}:/2308beget'
#
#    depends_on:
#      - db_mysql
#    networks:
#      - laravel




  2309livewire:
    container_name: 2309livewire
    depends_on:
      - db_mysql
    networks:
      - laravel
    build:
      context: .
      dockerfile: docker.2308beget.Dockerfile
    working_dir: ${FOLDER_2309LIVEWIRE_SERV}
    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data
      - FOLDER=${FOLDER_2309LIVEWIRE_SERV}
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - '${FOLDER_2309LIVEWIRE}:${FOLDER_2309LIVEWIRE_SERV}'





  test231116php:
    container_name: test231116php
#    depends_on:
#      - db_mysql
    networks:
      - laravel
    build:
      context: .
      dockerfile: docker.test231116php.Dockerfile
    working_dir: ${FOLDER_TEST23116PHP_SERV}
    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data
      - FOLDER=${FOLDER_TEST23116PHP_SERV}
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - '${FOLDER_TEST23116PHP}:${FOLDER_TEST23116PHP_SERV}'





#  test231012:
#    container_name: test231012
#    depends_on:
#      - db_mysql
##      - memcached
##      - redis
##    links:
##      - memcached:Memcached
#    networks:
#      - laravel
#    build:
#      context: .
#      dockerfile: ${TEST231012_DOCKERFILE}
#    working_dir: ${FOLDER_TEST231012_SERV}
#    environment:
#      - PHPGROUP=www-data
#      - PHPUSER=www-data
#    restart: unless-stopped
#    expose:
#      - 9000
#    volumes:
#      - '${FOLDER_TEST231012}:${FOLDER_TEST231012_SERV}'






# volumes:
#   caddy_certs:
# #   # scr:
# #   Caddyfile:
# #   # dataredis:
# #   v_mysql:
# #   data-www:
# #   www47:
# #   config:
# #   bu72_front:



networks:
  laravel:
    driver: bridge
  # ttt72_net: null
