# @enabled on
# @normal_password 111
# @admin_username admin
# @admin_password d033e22ae348aeb5660fc2140aec35850c4da997
# @normal_username user

webcontrol_interface 1
webcontrol_port 7999
setup_mode off
webcontrol_parms 2
webcontrol_localhost on
