name: Deploy bu docker


env:
  VPS_IP: 91.218.230.97
  VPS_USERNAME: root
  DIR: /home/docker
  GIT_BRANCH: origin/cicd_to_ihc_docker24


on:
  push:
    branches:
      - cicd_to_ihc_docker24



jobs:

  deploy:
    runs-on: ubuntu-latest
    outputs:
      rebuild_needed: ${{ steps.check_commit.outputs.rebuild }}
    steps:

      - name: Check commit message
        id: check_commit
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"[rebuild]"* ]]; then
            echo "rebuild_needed=true" >> $GITHUB_OUTPUT
          else
            echo "rebuild_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: "refresh git & restart docker"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_IP }}
          username: ${{ env.VPS_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY_DOCKER24 }}
          script: |
            cd ${{ env.DIR }}
            git fetch --all
            git reset --hard ${{ env.GIT_BRANCH }}

            # Обновление конфигурации Caddy
            docker cp ./caddy/Caddyfile caddy:/etc/caddy/Caddyfile
            docker exec caddy caddy reload --config /etc/caddy/Caddyfile

  deploy_composer:
    runs-on: ubuntu-latest
    needs: deploy
    strategy:
      matrix:
        include:
          - rebuild: ${{ needs.deploy.outputs.rebuild_needed }}
    steps:
      - uses: appleboy/ssh-action@master
        with:

          host: ${{ env.VPS_IP }}
          username: ${{ env.VPS_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY_DOCKER24 }}

          script: |
            cd ${{ env.DIR }}
            
            if [ "${{ matrix.rebuild }}" = "true" ]; then
              echo "Full rebuild started"
              make prod
              #docker-compose down
              #docker-compose up -d --build
            else
              echo "Normal update"
              make restart_caddy_prod
            fi

  sms_start:
    runs-on: ubuntu-latest
    steps:
      - name: send telega
        uses: appleboy/telegram-action@master
        with:
          # to: ${{ secrets.TELEGRAM_TO }}
          to: 360209578, phpcat,
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🐥🐥🐥 ${{ github.repository }} 
            ${{ github.event_name }} > ${{ github.event.head_commit.message }}
            👨🏻‍💻 ${{github.actor}} (${{ github.run_id }})

  sms_end:
    runs-on: ubuntu-latest
    # needs: [deploy_composer, deploy_npm]
    needs: deploy_composer

    steps:
      - name: send telega
        uses: appleboy/telegram-action@master
        with:
          # to: ${{ secrets.TELEGRAM_TO }}
          to: 360209578, phpcat,
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🍀🍀🍀 ${{ needs.deploy.outputs.rebuild_needed == 'true' && '🛠️🛠️🛠️ rebuild' || 'Обычное обновление' }} 
            ${{ github.repository }} 
            ${{ github.event_name }} > ${{ github.event.head_commit.message }}
            👨🏻‍💻 ${{github.actor}} (${{ github.run_id }})
